### PR TITLE
Manual: Digipeater/Igate symbol selection, updated links.

### PR DESCRIPTION
**Pull request by dandrzejewski**
* PhirePhly/aprx#39 - Updated links to point to Kenneth's site.
* PhirePhly/aprx#32 - Added digipeater/igate symbol selection section.

### CODE REVIEW

**Comment by PhirePhly** [comment]
Thanks. I haven't done a good job of scrubbing stale links and contact info from the Aprx source.

How did you generate the digi icons with over-lays? I've been looking for a clean way to do that.

As for the symbol guidance, I was very displeased that Bob took none of my input on what symbols should be recommended for new builds, and I'm not willing to recommend the use of E, L, P, V, or W overlays. The Aprx manual should recommend the symbols covered in my article: https://github.com/PhirePhly/aprs_notes/blob/master/digipeater_symbol_selection.md

**Comment by dandrzejewski** [comment]
OK. I'll update the document.

As for the symbols with overlays... I figured out how aprs.fi does it.  I used Chrome developer tools to figure out the URL for the I# symbol, and then extrapolated that for the others. I# ends up being http://d1dhsh1i77j8ju.cloudfront.net/s1/f24/I23I23.png.

Note that ascii hex 0x23 is #.  So just extrapolate that out to 123123.png, R23R23.png, etc.

It looks like for the "normal" digipeater symbol, he's just using a sprite from the symbol files he's made (https://github.com/hessu/aprs-symbols).

**Comment by dandrzejewski** [comment]
Updated the document and cleaned up the commits a little.

**Comment by PhirePhly** [comment]
Looks good. Thanks for the work! I cherry-picked your commit, so you'll want to reset your repo off my current head to keep your history clean. Ideally pull requests come from branches which you dispose of once the owner accepts it.

Clearly I need to hurry up on my plan to port the manual to LaTeX, which is more revision control friendly than odt so more than one of us can work on this at once.

**Pull request closed without merging**
