### PR TITLE
Detect FreeBSD, use FreeBSD date(1)

### PR DESCRIPTION
**Pull request by kevans91**
Apologies for missing this in my initial pass -- FreeBSD's `date(1)` is not compatible, argument-wise. We can test `uname` as a fairly primitive check to vaguely see if we're on a FreeBSD system and use the appropriate `date(1)` arguments, falling back to the otherwise expected GNU/Linux assumption otherwise.

This is the last nit I have with build system foo, I'll move on to actually launching `aprx` and figuring out if there are any kinks remaining. A cursory glance at the pretty awesome documentation and serial-handling bits leads me to believe there's probably not much further work needed for FreeBSD bring-up. The only `/dev` assumption seems to be the reasonable `/dev/null exists` assumption, and everything else looks pretty configurable.

### CODE REVIEW

**Comment by kevans91** [comment]
Whoops, omitted:

Tested with: FreeBSD-current
Tested with: Debian

**Comment by PhirePhly** [comment]
Looking broader, is there other platforms where we'd see BSD date instead of GNU date? Would it make sense to try and match any "*BSD*" in the UNAME for this substitution, or should we leave that for the chump who wants to build Aprx on the third platform?

**Comment by kevans91** [comment]
That's fair -- I hadn't looked into other platforms' date(1), but I've
arrived at the following list of confirmed BSD date(1) users:

* FreeBSD (Given)
* TrueOS (technically given -- closely FreeBSD-based)
* NetBSD
* OpenBSD
* DragonflyBSD
* Mac OS Sierra (Safe to assume earlier versions, as well -- OS X is
loosely BSD derived)

Given this list, I think it would be safe to amend my PR to look for "BSD"
or "Darwin" in `uname` and assume BSD date(1). There are other edge cases
(like TrueOS, I believe -- I don't have access to a TrueOS system at the
moment to test) that don't present themselves specifically as *BSD or
Darwin, but I'm not sure if it's important to address all of those with
uname tests.

It would be nice if there were an easy way to test whether date(1) has a
--date option or not, but I can't think of a way off the top of my head to
do this other than to just try a `date --date=0 | grep -i illegal`, and
that just feels dirty.

**Comment by PhirePhly** [comment]
date might come back with an error code which we could capture somehow, but if there isn't an obvious and clean solution, I'm ok with starting with just FreeBSD/Linux. I've been perfectly happy only supporting Linux for the last two years, and I'd gladly take only those two platforms if it means more attention to more important parts of the codebase than the build system.

**Comment by kevans91** [comment]
Oy, it's clearly time to go to sleep. =) Re-wrote this to fallback to BSD style on error and redirect stderr to /dev/null here as well. This works well enough that I can at least turn it into a port and any real errors cropping up won't be masked by false-positive errors.

**Comment by PhirePhly** [comment]
I liked the first version more, even though it only supported FreeBSD. Much more clear what was going on.

**Comment by kevans91** [comment]
Excellent, thanks! I'll be able to dork around with aprx here in the coming
weeks, so we'll see how the rest of this goes. =)

On Mar 21, 2017 11:11 PM, "Kenneth Finnegan" <notifications@github.com>
wrote:

Closed #46 <https://github.com/PhirePhly/aprx/pull/46>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PhirePhly/aprx/pull/46#event-1009794782>, or mute the
thread

**Pull request closed without merging**
